#!/usr/bin/env bash

set -e

BASHLIB="`find $PWD -type d | grep -E '/(bin|lib)$' | xargs -n1 printf "%s:"`"
PATH="$BASHLIB:$PATH"

source bash+ :std

TMP=$PWD/tmp
BEGIN_PWD=$PWD

rm -fr $TMP
mkdir $TMP
export PERL5LIB="$PWD/lib:$PERL5LIB"

cd $TMP

teardown() {
  cd $BEGIN_PWD
  rm -fr $TMP
  return 0
}
